package updatecontact;

import javax.swing.JOptionPane;

import displaycontacts.DisplayAllContacts;
import model.Contact;
import phonebook.LinkedList;
import validations.AuthenticationFunctions;

public class UpdateContact extends javax.swing.JFrame {
    public static LinkedList contacts;
    public static Contact contact;
    public static String loggedInUserID;

    /**
     * Creates new form UpdateContact
     */
    public UpdateContact(LinkedList contacts, Contact contact, String loggedInUserID) {
        UpdateContact.contacts = contacts;
        UpdateContact.contact = contact;
        UpdateContact.loggedInUserID = loggedInUserID;

        initComponents();

        this.txtFirstName.setText(UpdateContact.contact.getFirstName());
        this.txtLastName.setText(UpdateContact.contact.getLastName());
        this.txtPhoneNumber.setText(UpdateContact.contact.getPhoneNumber());
        this.txtEmail.setText(UpdateContact.contact.getEmail());
        this.txtPhysicalAddress.setText(UpdateContact.contact.getAddress());
        this.txtContactGroup.setText(UpdateContact.contact.getContactGroup());

        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        txtContact = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblPhysicalAdress = new javax.swing.JLabel();
        txtPhysicalAddress = new javax.swing.JTextField();
        btnUpdateContact = new javax.swing.JToggleButton();
        lblContactGroup = new javax.swing.JLabel();
        txtContactGroup = new javax.swing.JTextField();
        btnContactsList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(436, 372));

        pnlMain.setBackground(new java.awt.Color(232, 248, 245));

        txtContact.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtContact.setForeground(new java.awt.Color(93, 58, 155));
        txtContact.setText("Existing contact");

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(93, 58, 155));
        lblFirstName.setText("First Name");

        lblLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(93, 58, 155));
        lblLastName.setText("Last Name");

        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(93, 58, 155));
        lblPhoneNumber.setText("Phone Number");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(93, 58, 155));
        lblEmail.setText("Email");

        txtFirstName.setBackground(new java.awt.Color(250, 250, 250));
        txtFirstName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(72, 217, 141));
        txtFirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 3, true));

        txtLastName.setBackground(new java.awt.Color(250, 250, 250));
        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(72, 217, 141));
        txtLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 3, true));

        txtPhoneNumber.setBackground(new java.awt.Color(250, 250, 250));
        txtPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(72, 217, 141));
        txtPhoneNumber.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 3, true));

        txtEmail.setBackground(new java.awt.Color(250, 250, 250));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(72, 217, 141));
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 3, true));

        lblPhysicalAdress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhysicalAdress.setForeground(new java.awt.Color(93, 58, 155));
        lblPhysicalAdress.setText("Physical Address");

        txtPhysicalAddress.setBackground(new java.awt.Color(250, 250, 250));
        txtPhysicalAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPhysicalAddress.setForeground(new java.awt.Color(72, 217, 141));
        txtPhysicalAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 3, true));

        btnUpdateContact.setBackground(new java.awt.Color(255, 111, 97));
        btnUpdateContact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateContact.setForeground(new java.awt.Color(250, 250, 250));
        btnUpdateContact.setText("Update contact");
        btnUpdateContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateContactMouseClicked(evt);
            }
        });

        lblContactGroup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContactGroup.setForeground(new java.awt.Color(93, 58, 155));
        lblContactGroup.setText("Contact Group");

        txtContactGroup.setBackground(new java.awt.Color(250, 250, 250));
        txtContactGroup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContactGroup.setForeground(new java.awt.Color(72, 217, 141));
        txtContactGroup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(250, 250, 250), 3, true));

        btnContactsList.setBackground(new java.awt.Color(250, 250, 250));
        btnContactsList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnContactsList.setForeground(new java.awt.Color(255, 111, 97));
        btnContactsList.setText("Contacts list");
        btnContactsList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContactsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContactsListMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(lblPhoneNumber)
                        .addGap(90, 90, 90)
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(lblPhysicalAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(lblContactGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(txtPhysicalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtContactGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContact))
                        .addGap(47, 47, 47)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(btnContactsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnUpdateContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContact)
                    .addComponent(btnContactsList))
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblFirstName)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoneNumber)
                    .addComponent(lblEmail))
                .addGap(6, 6, 6)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhysicalAdress)
                    .addComponent(lblContactGroup))
                .addGap(6, 6, 6)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhysicalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContactGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnUpdateContact)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContactsListMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnContactsListMouseClicked
        this.dispose();
        new DisplayAllContacts(contacts);
    }// GEN-LAST:event_btnContactsListMouseClicked

    private void btnUpdateContactMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnUpdateContactMouseClicked
        String firstName = txtFirstName.getText().trim();
        String lastName = txtLastName.getText().trim();
        String phoneNumber = txtPhoneNumber.getText().trim();
        String email = txtEmail.getText().trim();
        String physicalAddress = txtPhysicalAddress.getText().trim();
        String contactGroup = txtContactGroup.getText().trim();

        // Validate mandatory fields
        if (!AuthenticationFunctions.validateName(firstName, "First Name"))
            return;
        if (!AuthenticationFunctions.validatePhoneNumber(phoneNumber))
            return;

        // Validate optional fields only if they are not empty
        if (!lastName.isEmpty() && !AuthenticationFunctions.validateName(lastName, "Last Name"))
            return;
        if (!email.isEmpty() && !AuthenticationFunctions.validateEmail(email))
            return;
        if (!physicalAddress.isEmpty() && !AuthenticationFunctions.validatePhysicalAddress(physicalAddress))
            return;
        if (!contactGroup.isEmpty() && !AuthenticationFunctions.validateContactGroup(contactGroup))
            return;

        // Find the contact to update in the linked list using phone number
        Contact contactToUpdate = contact; // Assuming `contact` is already fetched

        // Update the contact details in the linked list
        contactToUpdate.setFirstName(firstName);
        contactToUpdate.setLastName(lastName);
        contactToUpdate.setEmail(email);
        contactToUpdate.setAddress(physicalAddress);
        contactToUpdate.setContactGroup(contactGroup);

        // Update the contact in the CSV file
        AuthenticationFunctions.updateContactInCSV(contacts, contactToUpdate, "src/storage/contact.csv");

        JOptionPane.showMessageDialog(this, "Contact successfully updated!", "Success",
                JOptionPane.INFORMATION_MESSAGE);

        this.dispose();
        new DisplayAllContacts(contacts);
    }// GEN-LAST:event_btnUpdateContactMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateContact.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateContact.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateContact.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateContact.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateContact(UpdateContact.contacts, UpdateContact.contact, UpdateContact.loggedInUserID)
                        .setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContactsList;
    private javax.swing.JToggleButton btnUpdateContact;
    private javax.swing.JLabel lblContactGroup;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhysicalAdress;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JLabel txtContact;
    private javax.swing.JTextField txtContactGroup;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhysicalAddress;
    // End of variables declaration//GEN-END:variables
}

/**
 *
 * @author: < Eurico Dande - 223134902 />
 */